### ISSUE TITLE
TypeError not a funtion from React 

### ISSUE THREAD

**Issue by DannyLeeBeasley** [learn-co-curriculum/phase-4-rails-create-read-lab#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas
https://learning.flatironschool.com/courses/4207/assignments/135822?module_item_id=281621

## Describe the bug

Line 24 in the PlantPage component is throwing a TypeError: plants.filter is not a function. Can't see why this would be happening... 

## What is the expected behavior?

Page load

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X

## Any additional context?

<img width="656" alt="Screen Shot 2021-08-11 at 4 54 08 PM" src="https://user-images.githubusercontent.com/79606324/129108779-d842eaa2-b689-4994-b11e-5b84c09d5d16.png">

**Comment by graciemcguire** [comment]
Hi there, 

Thanks for raising this issue. Based on your description, it sounds like this issue may be related to solving this lab, rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved! 💙

**Comment by DannyLeeBeasley** [comment]
Hi Gracie,

I solved the lab and all the tests passed, but when I tried to look at the
frontend as prompted in the ReadMe to see how the routes I set up were
working, the React app threw this error. I never touched the React app at
all.

Thanks,

Dan

**Comment by graciemcguire** [comment]
Hey Dan - I am still having trouble recreating your issue, so I'm going to leave the issue closed for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment, please reopen the issue and I'd be happy to take a second look!

Thanks!
